# hru_hru_launcher/config/resources.py

ALERT_ICON_SVG = b'''<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-shield-alert"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/><path d="M12 8v4"/><path d="M12 16h.01"/></svg>'''

PLAY_ICON_SVG = b'''<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" stroke="#ffffff" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-play"><polygon points="5 3 19 12 5 21 5 3"/></svg>'''
SETTINGS_ICON_SVG = b'''<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" stroke="#ffffff" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-settings"><circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 0 1 0 2.83 2 2 0 0 1-2.83 0l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 0 1-2 2 2 2 0 0 1-2-2v-.09A1.65 1.65 0 0 0 9 19.4a1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 0 1-2.83 0 2 2 0 0 1 0-2.83l.06-.06a1.65 1.65 0 0 0 .33-1.82 1.65 1.65 0 0 0-1.51-1H3a2 2 0 0 1-2-2 2 2 0 0 1 2-2h.09A1.65 1.65 0 0 0 4.6 9a1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 0 1 0-2.83 2 2 0 0 1 2.83 0l.06.06a1.65 1.65 0 0 0 1.82.33H9a1.65 1.65 0 0 0 1-1.51V3a2 2 0 0 1 2-2 2 2 0 0 1 2 2v.09a1.65 1.65 0 0 0 1 1.51 1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 0 1 2.83 0 2 2 0 0 1 0 2.83l-.06.06a1.65 1.65 0 0 0-.33 1.82V9a1.65 1.65 0 0 0 1.51 1H21a2 2 0 0 1 2 2 2 2 0 0 1-2 2h-.09a1.65 1.65 0 0 0-1.51 1z"/></svg>'''
NEWS_ICON_SVG = b'''<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" stroke="#ffffff" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-newspaper"><path d="M4 3h16a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2z"/><line x1="18" y1="10" x2="12" y2="10"/><line x1="18" y1="14" x2="12" y2="14"/><line x1="6" y1="10" x2="6.01" y2="10"/><line x1="6" y1="14" x2="6.01" y2="14"/></svg>'''
CONSOLE_ICON_SVG = b'''<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" stroke="#ffffff" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-terminal"><path d="M4 5l6 6-6 6"/><line x1="12" y1="19" x2="20" y2="19"/></svg>'''
VERSION_ICON_SVG = b'''<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" stroke="#ffffff" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-package"><path d="M16.5 9.4L7.5 4.21"/><path d="M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z"/><path d="M3.27 6.96L12 12.01 20.73 6.96"/><line x1="12" y1="22.08" x2="12" y2="12"/></svg>'''
USERNAME_ICON_SVG = b'''<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" stroke="#ffffff" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-user"><path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"/><circle cx="12" cy="7" r="4"/></svg>'''
MODS_ICON_SVG = b'''<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" stroke="#ffffff" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-folder-plus"><path d="M22 19a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h5l2 3h9a2 2 0 0 1 2 2z"/><line x1="12" y1="11" x2="12" y2="17"/><line x1="9" y1="14" x2="15" y2="14"/></svg>'''
MODPACKS_ICON_SVG = b'''<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" stroke="#ffffff" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-grid"><rect x="3" y="3" width="7" height="7"/><rect x="14" y="3" width="7" height="7"/><rect x="14" y="14" width="7" height="7"/><rect x="3" y="14" width="7" height="7"/></svg>'''
VPN_ICON_SVG = b'''<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" stroke="#ffffff" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-shield"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/></svg>'''
INSTALLED_ICON_SVG = b'''<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" stroke="#1DB954" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-check-circle"><circle cx="12" cy="12" r="10"/><path d="M9 12l2 2 4-4"/></svg>'''
LINK_ICON_SVG = b'''<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-external-link"><path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6"/><polyline points="15 3 21 3 21 9"/><line x1="10" y1="14" x2="21" y2="3"/></svg>'''
DELETE_ICON_SVG = b'''<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" stroke="#E23D28" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-trash-2"><polyline points="3 6 5 6 21 6"/><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"/><line x1="10" y1="11" x2="10" y2="17"/><line x1="14" y1="11" x2="14" y2="17"/></svg>'''
CHECK_ICON_SVG = b'''<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" stroke="#ffffff" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-check"><path d="M5 13l4 4L19 7"/></svg>'''

LANGUAGES = {
    "ru": {
        "title": "Hru Hru Launcher",
        "version": "Версия",
        "username": "Никнейм",
        "enter_username": "Введите никнейм...",
        "enter_username_error": "Ошибка: Введите никнейм!",
        "launch": "ИГРАТЬ",
        "launching": "ЗАПУСК...",
        "news": "Новости",
        "mods": "Моды",
        "modpacks": "Сборки",
        "vpn": "VPN",
        "console": "Консоль",
        "settings": "Настройки",
        "language": "Язык",
        "accent_color": "Акцентный цвет",
        "choose_color": "Выбрать цвет",
        "memory": "Выделение памяти",
        "fullscreen": "Полноэкранный режим",
        "close_launcher": "Закрывать лаунчер после запуска",
        "clear_console": "Очистить консоль",
        "advanced_settings_show": "Показать расширенные настройки",
        "resolution": "Разрешение игры",
        "jvm_args_custom": "Пользовательские аргументы JVM",
        "java_path": "Путь к исполняемому файлу Java",
        "version_type": "Тип версии",
        "vanilla": "Vanilla",
        "forge": "Forge",
        "fabric": "Fabric",
        "loading_versions": "Загрузка версий...",
        "mem_feedback_risky": "Рискованно! Может не хватить для запуска.",
        "mem_feedback_low": "Мало. Подойдет для старых версий.",
        "mem_feedback_optimal": "Оптимально для большинства сборок.",
        "mem_feedback_good": "Отлично для тяжелых сборок.",
        "mem_feedback_excessive": "Избыточно. Может вызвать микро-лаги.",
        "wip_notice": "Раздел в разработке",
        "open_mods_folder": "Открыть папку модов",
        "open_modpacks_folder": "Открыть папку сборок",
        "search_mods_placeholder": "Найти моды на Modrinth...",
        "searching": "Поиск...",
        "select_mod_loader": "Сначала выберите загрузчик (Forge/Fabric).",
        "no_mods_found": "Моды не найдены.",
        "sort_by": "Сортировка:",
        "relevance": "По релевант.",
        "downloads": "По популярности",
        "newest": "По новизне",
        "refresh": "Обновить",
        "downloading": "Загрузка",
        "starting": "Запуск игры...",
        "error_occurred": "Произошла ошибка: ",
        "error_dialog_title": "Обнаружена Ошибка",
        "fix_button": "Исправить",
        "cancel_button": "Отмена",
        
        "error_file_corruption_title": "Повреждение Файлов",
        "error_file_corruption_desc": "Похоже, что основные файлы версии '{version_id}' повреждены или отсутствуют.",
        "error_file_corruption_fix": "Рекомендуется полностью переустановить эту версию. Все ваши миры и настройки сохранятся.",
        
        "error_java_path_title": "Неверный Путь Java",
        "error_java_path_desc": "Лаунчер не смог найти Java по указанному пути.",
        "error_java_path_fix": "Предлагается сбросить путь к Java на автоматическое определение и повторить запуск.",
        
        "error_jvm_args_title": "Неверный Аргумент JVM",
        "error_jvm_args_desc": "Игра не запустилась из-за неверного аргумента, переданного Java.",
        "error_jvm_args_fix": "Рекомендуется очистить поле пользовательских аргументов JVM в настройках.",
        
        "error_manual_java_path_desc": "Лаунчер не смог автоматически найти рабочую версию Java на вашем компьютере.",
        "error_manual_java_path_fix": "Убедитесь, что у вас установлена Java (17+), и попробуйте указать путь к файлу 'javaw.exe' вручную в расширенных настройках.",

                "news_disclaimer": "Официальные новости с сайта Minecraft.net (не относятся к лаунчеру)",
        "read_more": "Читать далее...",
        "loading_news": "Загрузка новостей...",
        
        "mods_search": "Поиск",
        "mods_installed": "Установленные",
        "installed_mods_scan": "Сканирование папки модов...",
        "installed_mods_empty": "Папка 'mods' пуста.",
        "mod_enabled": "Включен",
        "mod_disabled": "Выключен",
        "delete_mod_confirm_title": "Удаление мода",
        "delete_mod_confirm_text": "Вы уверены, что хотите удалить файл мода '{filename}'?",
    },
    "en": {
        "title": "Hru Hru Launcher",
        "version": "Version",
        "username": "Username",
        "enter_username": "Enter username...",
        "enter_username_error": "Error: Enter a username!",
        "launch": "PLAY",
        "launching": "LAUNCHING...",
        "news": "News",
        "mods": "Mods",
        "modpacks": "Modpacks",
        "vpn": "VPN",
        "console": "Console",
        "settings": "Settings",
        "language": "Language",
        "accent_color": "Accent Color",
        "choose_color": "Choose color",
        "memory": "Memory Allocation",
        "fullscreen": "Fullscreen mode",
        "close_launcher": "Close launcher after game starts",
        "clear_console": "Clear Console",
        "advanced_settings_show": "Show advanced settings",
        "resolution": "Game Resolution",
        "jvm_args_custom": "Custom JVM Arguments",
        "java_path": "Java Executable Path",
        "version_type": "Version Type",
        "vanilla": "Vanilla",
        "forge": "Forge",
        "fabric": "Fabric",
        "loading_versions": "Loading versions...",
        "mem_feedback_risky": "Risky! Might not be enough to launch.",
        "mem_feedback_low": "Low. Suitable for older versions.",
        "mem_feedback_optimal": "Optimal for most modpacks.",
        "mem_feedback_good": "Great for heavy modpacks.",
        "mem_feedback_excessive": "Excessive. May cause micro-stutters.",
        "wip_notice": "Section under construction",
        "open_mods_folder": "Open mods folder",
        "open_modpacks_folder": "Open modpacks folder",
        "search_mods_placeholder": "Search for mods on Modrinth...",
        "searching": "Searching...",
        "select_mod_loader": "First, select a loader (Forge/Fabric).",
        "no_mods_found": "No mods found.",
        "sort_by": "Sort by:",
        "relevance": "Relevance",
        "downloads": "Popularity",
        "newest": "Newest",
        "refresh": "Refresh",
        "downloading": "Downloading",
        "starting": "Starting game...",
        "error_occurred": "An error occurred: ",
        "error_dialog_title": "Error Detected",
        "fix_button": "Fix It",
        "cancel_button": "Cancel",
        
        "error_file_corruption_title": "File Corruption",
        "error_file_corruption_desc": "It seems the core files for version '{version_id}' are corrupt or missing.",
        "error_file_corruption_fix": "It is recommended to completely reinstall this version. All your worlds and settings will be saved.",
        
        "error_java_path_title": "Invalid Java Path",
        "error_java_path_desc": "The launcher could not find Java at the specified path.",
        "error_java_path_fix": "We suggest resetting the Java path to automatic detection and trying to launch again.",
        
        "error_jvm_args_title": "Invalid JVM Argument",
        "error_jvm_args_desc": "The game failed to launch due to an incorrect argument passed to Java.",
        "error_jvm_args_fix": "It is recommended to clear the custom JVM arguments field in the settings.",
        
        "error_manual_java_path_desc": "The launcher could not automatically find a working Java installation on your computer.",
        "error_manual_java_path_fix": "Please ensure Java (17+) is installed, and try specifying the path to 'javaw.exe' manually in the advanced settings.",
        
        "news_disclaimer": "Official news from Minecraft.net (not related to the launcher)",
        "read_more": "Read More...",
        "loading_news": "Loading news...",

        "mods_search": "Search",
        "mods_installed": "Installed",
        "installed_mods_scan": "Scanning mods folder...",
        "installed_mods_empty": "Your 'mods' folder is empty.",
        "mod_enabled": "Enabled",
        "mod_disabled": "Disabled",
        "delete_mod_confirm_title": "Delete Mod",
        "delete_mod_confirm_text": "Are you sure you want to delete the mod file '{filename}'?",
    }
}