# hru_hru_launcher/config/resources.py

ALERT_ICON_SVG = b'''<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-shield-alert"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/><path d="M12 8v4"/><path d="M12 16h.01"/></svg>'''
PLAY_ICON_SVG = b'''<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" stroke="#ffffff" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-play"><polygon points="5 3 19 12 5 21 5 3"/></svg>'''
SETTINGS_ICON_SVG = b'''<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" stroke="#ffffff" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-settings"><circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 0 1 0 2.83 2 2 0 0 1-2.83 0l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 0 1-2 2 2 2 0 0 1-2-2v-.09A1.65 1.65 0 0 0 9 19.4a1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 0 1-2.83 0 2 2 0 0 1 0-2.83l.06-.06a1.65 1.65 0 0 0 .33-1.82 1.65 1.65 0 0 0-1.51-1H3a2 2 0 0 1-2-2 2 2 0 0 1 2-2h.09A1.65 1.65 0 0 0 4.6 9a1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 0 1 0-2.83 2 2 0 0 1 2.83 0l.06.06a1.65 1.65 0 0 0 1.82.33H9a1.65 1.65 0 0 0 1-1.51V3a2 2 0 0 1 2-2 2 2 0 0 1 2 2v.09a1.65 1.65 0 0 0 1 1.51 1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 0 1 2.83 0 2 2 0 0 1 0 2.83l-.06.06a1.65 1.65 0 0 0-.33 1.82V9a1.65 1.65 0 0 0 1.51 1H21a2 2 0 0 1 2 2 2 2 0 0 1-2 2h-.09a1.65 1.65 0 0 0-1.51 1z"/></svg>'''
NEWS_ICON_SVG = b'''<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" stroke="#ffffff" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-newspaper"><path d="M4 3h16a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2z"/><line x1="18" y1="10" x2="12" y2="10"/><line x1="18" y1="14" x2="12" y2="14"/><line x1="6" y1="10" x2="6.01" y2="10"/><line x1="6" y1="14" x2="6.01" y2="14"/></svg>'''
CONSOLE_ICON_SVG = b'''<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" stroke="#ffffff" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-terminal"><path d="M4 5l6 6-6 6"/><line x1="12" y1="19" x2="20" y2="19"/></svg>'''
VERSION_ICON_SVG = b'''<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" stroke="#ffffff" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-package"><path d="M16.5 9.4L7.5 4.21"/><path d="M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z"/><path d="M3.27 6.96L12 12.01 20.73 6.96"/><line x1="12" y1="22.08" x2="12" y2="12"/></svg>'''
USERNAME_ICON_SVG = b'''<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" stroke="#ffffff" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-user"><path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"/><circle cx="12" cy="7" r="4"/></svg>'''
MODS_ICON_SVG = b'''<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" stroke="#ffffff" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-folder-plus"><path d="M22 19a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h5l2 3h9a2 2 0 0 1 2 2z"/><line x1="12" y1="11" x2="12" y2="17"/><line x1="9" y1="14" x2="15" y2="14"/></svg>'''
MODPACKS_ICON_SVG = b'''<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" stroke="#ffffff" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-grid"><rect x="3" y="3" width="7" height="7"/><rect x="14" y="3" width="7" height="7"/><rect x="14" y="14" width="7" height="7"/><rect x="3" y="14" width="7" height="7"/></svg>'''
VPN_ICON_SVG = b'''<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" stroke="#ffffff" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-shield"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/></svg>'''
INSTALLED_ICON_SVG = b'''<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" stroke="#1DB954" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-check-circle"><circle cx="12" cy="12" r="10"/><path d="M9 12l2 2 4-4"/></svg>'''
FOLDER_ICON_SVG = b'''<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#f8f8f2" viewBox="0 0 256 256"><path d="M224,88H72A71.76,71.76,0,0,0,16,152v32a8,8,0,0,0,8,8H224a8,8,0,0,0,8-8V96A8,8,0,0,0,224,88ZM48,152A23.82,23.82,0,0,1,72,128h144v24H72A24,24,0,0,1,48,152Zm168-48H188.38a40,40,0,0,0-76.76,0H72A23.82,23.82,0,0,1,48,128.39V128a55.75,55.75,0,0,1,.77-9.08l13.14-48.62A8,8,0,0,1,70,64H208a8,8,0,0,1,7.1,4.63l18.81,47C239.41,121.28,232,128,224,128a7.78,7.78,0,0,0-2.18-.27V104Z"></path></svg>'''


LANGUAGES = {
    "ru": {
        "title": "Hru Hru Launcher",
        "version": "Версия",
        "username": "Никнейм",
        "enter_username": "Введите никнейм...",
        "enter_username_error": "Ошибка: Введите никнейм!",
        "launch": "ИГРАТЬ",
        "launching": "ЗАПУСК...",
        "news": "Новости",
        "mods": "Моды",
        "modpacks": "Сборки",
        "vpn": "VPN",
        "console": "Консоль",
        "settings": "Настройки",
        "language": "Язык",
        "accent_color": "Акцентный цвет",
        "choose_color": "Выбрать цвет",
        "memory": "Выделение памяти",
        "fullscreen": "Полноэкранный режим",
        "close_launcher": "Закрывать лаунчер после запуска",
        "clear_console": "Очистить консоль",
        "advanced_settings_show": "Показать расширенные настройки",
        "resolution": "Разрешение игры",
        "jvm_args_custom": "Пользовательские аргументы JVM",
        "java_path": "Путь к исполняемому файлу Java",
        "version_type": "Тип версии",
        "vanilla": "Vanilla",
        "forge": "Forge",
        "fabric": "Fabric",
        "loading_versions": "Загрузка версий...",
        "mem_feedback_risky": "Рискованно! Может не хватить для запуска.",
        "mem_feedback_low": "Мало. Подойдет для старых версий.",
        "mem_feedback_optimal": "Оптимально для большинства сборок.",
        "mem_feedback_good": "Отлично для тяжелых сборок.",
        "mem_feedback_excessive": "Избыточно. Может вызвать микро-лаги.",
        "wip_notice": "Раздел в разработке",
        "open_mods_folder": "Открыть папку модов",
        "open_modpacks_folder": "Открыть папку сборок",
        "search_mods_placeholder": "Найти моды на Modrinth...",
        "searching": "Поиск...",
        "select_mod_loader": "Сначала выберите загрузчик (Forge/Fabric).",
        "no_mods_found": "Моды не найдены.",
        "sort_by": "Сортировка:",
        "relevance": "По релевант.",
        "downloads": "По популярности",
        "newest": "По новизне",
        "refresh": "Обновить",
        "page": "Стр.",
        "prev_page": "Назад",
        "next_page": "Вперед",
        "downloading": "Загрузка",
        "starting": "Запуск игры...",
        "error_occurred": "Произошла ошибка: ",
        "error_dialog_title": "Обнаружена Ошибка",
        "fix_button": "Исправить",
        "cancel_button": "Отмена",
        "error_file_corruption_title": "Повреждение Файлов",
        "error_file_corruption_desc": "Похоже, что основные файлы версии '{version_id}' повреждены или отсутствуют.",
        "error_file_corruption_fix": "Рекомендуется полностью переустановить эту версию. Все ваши миры и настройки сохранятся.",
        "error_java_path_title": "Неверный Путь Java",
        "error_java_path_desc": "Лаунчер не смог найти Java по указанному пути.",
        "error_java_path_fix": "Предлагается сбросить путь к Java на автоматическое определение и повторить запуск.",
        "error_jvm_args_title": "Неверный Аргумент JVM",
        "error_jvm_args_desc": "Игра не запустилась из-за неверного аргумента, переданного Java.",
        "error_jvm_args_fix": "Рекомендуется очистить поле пользовательских аргументов JVM в настройках.",
        "error_manual_java_path_desc": "Лаунчер не смог автоматически найти рабочую версию Java на вашем компьютере.",
        "error_manual_java_path_fix": "Убедитесь, что у вас установлена Java (17+), и попробуйте указать путь к файлу 'javaw.exe' вручную в расширенных настройках.",
        # Нові рядки для логування
        "error_searching_mods": "Ошибка при поиске модов ('{query}'): {e}",
        "error_getting_project_details": "Не удалось получить детали проекта {project_id}: {e}",
        "error_reading_mod_id": "Не удалось прочитать mod ID из {filename}: {e}",
        "error_finding_mod_version": "Не удалось найти версию для {project_id} (MC {game_version}, {loader}): {e}",
        "file_downloaded_successfully": "Файл {filename} успешно скачан.",
        "error_downloading_file": "Ошибка скачивания {filename}: {e}",
        "search": "Поиск",
        "installed": "Установленные",
        "scanning": "Сканирование...",
        "no_local_mods_found": "Моды в папке не найдены.",
    },
    "en": {
        "title": "Hru Hru Launcher",
        "version": "Version",
        "username": "Username",
        "enter_username": "Enter username...",
        "enter_username_error": "Error: Enter a username!",
        "launch": "PLAY",
        "launching": "LAUNCHING...",
        "news": "News",
        "mods": "Mods",
        "modpacks": "Modpacks",
        "vpn": "VPN",
        "console": "Console",
        "settings": "Settings",
        "language": "Language",
        "accent_color": "Accent Color",
        "choose_color": "Choose color",
        "memory": "Memory Allocation",
        "fullscreen": "Fullscreen mode",
        "close_launcher": "Close launcher after game starts",
        "clear_console": "Clear Console",
        "advanced_settings_show": "Show advanced settings",
        "resolution": "Game Resolution",
        "jvm_args_custom": "Custom JVM Arguments",
        "java_path": "Java Executable Path",
        "version_type": "Version Type",
        "vanilla": "Vanilla",
        "forge": "Forge",
        "fabric": "Fabric",
        "loading_versions": "Loading versions...",
        "mem_feedback_risky": "Risky! Might not be enough to launch.",
        "mem_feedback_low": "Low. Suitable for older versions.",
        "mem_feedback_optimal": "Optimal for most modpacks.",
        "mem_feedback_good": "Great for heavy modpacks.",
        "mem_feedback_excessive": "Excessive. May cause micro-stutters.",
        "wip_notice": "Section under construction",
        "open_mods_folder": "Open mods folder",
        "open_modpacks_folder": "Open modpacks folder",
        "search_mods_placeholder": "Search for mods on Modrinth...",
        "searching": "Searching...",
        "select_mod_loader": "First, select a loader (Forge/Fabric).",
        "no_mods_found": "No mods found.",
        "sort_by": "Sort by:",
        "relevance": "Relevance",
        "downloads": "Popularity",
        "newest": "Newest",
        "refresh": "Refresh",
        "page": "Page",
        "prev_page": "Prev",
        "next_page": "Next",
        "downloading": "Downloading",
        "starting": "Starting game...",
        "error_occurred": "An error occurred: ",
        "error_dialog_title": "Error Detected",
        "fix_button": "Fix It",
        "cancel_button": "Cancel",
        "error_file_corruption_title": "File Corruption",
        "error_file_corruption_desc": "It seems the core files for version '{version_id}' are corrupt or missing.",
        "error_file_corruption_fix": "It is recommended to completely reinstall this version. All your worlds and settings will be saved.",
        "error_java_path_title": "Invalid Java Path",
        "error_java_path_desc": "The launcher could not find Java at the specified path.",
        "error_java_path_fix": "We suggest resetting the Java path to automatic detection and trying to launch again.",
        "error_jvm_args_title": "Invalid JVM Argument",
        "error_jvm_args_desc": "The game failed to launch due to an incorrect argument passed to Java.",
        "error_jvm_args_fix": "It is recommended to clear the custom JVM arguments field in the settings.",
        "error_manual_java_path_desc": "The launcher could not automatically find a working Java installation on your computer.",
        "error_manual_java_path_fix": "Please ensure Java (17+) is installed, and try specifying the path to 'javaw.exe' manually in the advanced settings.",
        # New lines for logging
        "error_searching_mods": "Error searching for mods ('{query}'): {e}",
        "error_getting_project_details": "Failed to get project details for {project_id}: {e}",
        "error_reading_mod_id": "Could not read mod ID from {filename}: {e}",
        "error_finding_mod_version": "Could not find a version for {project_id} (MC {game_version}, {loader}): {e}",
        "file_downloaded_successfully": "File {filename} downloaded successfully.",
        "error_downloading_file": "Error downloading {filename}: {e}",
        "search": "Search",
        "installed": "Installed",
        "scanning": "Scanning...",
        "no_local_mods_found": "No mods found in folder.",
    },
    "ua": {
        "title": "Hru Hru Launcher",
        "version": "Версія",
        "username": "Нікнейм",
        "enter_username": "Введіть нікнейм...",
        "enter_username_error": "Помилка: Введіть нікнейм!",
        "launch": "ГРАТИ",
        "launching": "ЗАПУСК...",
        "news": "Новини",
        "mods": "Моди",
        "modpacks": "Збірки",
        "vpn": "VPN",
        "console": "Консоль",
        "settings": "Налаштування",
        "language": "Мова",
        "accent_color": "Акцентний колір",
        "choose_color": "Обрати колір",
        "memory": "Виділення пам'яті",
        "fullscreen": "Повноекранний режим",
        "close_launcher": "Закривати лаунчер після запуску",
        "clear_console": "Очистити консоль",
        "advanced_settings_show": "Показати розширені налаштування",
        "resolution": "Роздільна здатність гри",
        "jvm_args_custom": "Власні аргументи JVM",
        "java_path": "Шлях до файлу Java",
        "version_type": "Тип версії",
        "vanilla": "Vanilla",
        "forge": "Forge",
        "fabric": "Fabric",
        "loading_versions": "Завантаження версій...",
        "mem_feedback_risky": "Ризиковано! Може не вистачити для запуску.",
        "mem_feedback_low": "Мало. Підійде для старих версій.",
        "mem_feedback_optimal": "Оптимально для більшості збірок.",
        "mem_feedback_good": "Чудово для важких збірок.",
        "mem_feedback_excessive": "Надлишково. Може викликати мікро-лаги.",
        "wip_notice": "Розділ у розробці",
        "open_mods_folder": "Відкрити папку модів",
        "open_modpacks_folder": "Відкрити папку збірок",
        "search_mods_placeholder": "Знайти моди на Modrinth...",
        "searching": "Пошук...",
        "select_mod_loader": "Спочатку виберіть завантажувач (Forge/Fabric).",
        "no_mods_found": "Моди не знайдено.",
        "sort_by": "Сортувати за:",
        "relevance": "За релевантн.",
        "downloads": "За популярністю",
        "newest": "За новизною",
        "refresh": "Оновити",
        "page": "Стор.",
        "prev_page": "Назад",
        "next_page": "Вперед",
        "downloading": "Завантаження",
        "starting": "Запуск гри...",
        "error_occurred": "Сталася помилка: ",
        "error_dialog_title": "Виявлено Помилку",
        "fix_button": "Виправити",
        "cancel_button": "Скасувати",
        "error_file_corruption_title": "Пошкодження Файлів",
        "error_file_corruption_desc": "Схоже, що основні файли версії '{version_id}' пошкоджені або відсутні.",
        "error_file_corruption_fix": "Рекомендується повністю перевстановити цю версію. Усі ваші світи та налаштування збережуться.",
        "error_java_path_title": "Неправильний Шлях Java",
        "error_java_path_desc": "Лаунчер не зміг знайти Java за вказаним шляхом.",
        "error_java_path_fix": "Пропонується скинути шлях до Java на автоматичне визначення та повторити запуск.",
        "error_jvm_args_title": "Неправильний Аргумент JVM",
        "error_jvm_args_desc": "Гра не запустилася через невірний аргумент, переданий Java.",
        "error_jvm_args_fix": "Рекомендується очистити поле власних аргументів JVM у налаштуваннях.",
        "error_manual_java_path_desc": "Лаунчер не зміг автоматично знайти робочу версію Java на вашому комп'ютері.",
        "error_manual_java_path_fix": "Переконайтеся, що у вас встановлена Java (17+), і спробуйте вказати шлях до файлу 'javaw.exe' вручну в розширених налаштуваннях.",
        # Нові рядки для логування
        "error_searching_mods": "Помилка під час пошуку модів ('{query}'): {e}",
        "error_getting_project_details": "Не вдалося отримати деталі проекту {project_id}: {e}",
        "error_reading_mod_id": "Не вдалося прочитати mod ID з {filename}: {e}",
        "error_finding_mod_version": "Не вдалося знайти версію для {project_id} (MC {game_version}, {loader}): {e}",
        "file_downloaded_successfully": "Файл {filename} успішно завантажено.",
        "error_downloading_file": "Помилка завантаження {filename}: {e}",
        "search": "Пошук",
        "installed": "Встановлені",
        "scanning": "Сканування...",
        "no_local_mods_found": "Моди в папці не знайдено.",
    }
}